# Generated by Django 4.0.5 on 2022-07-29 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_debetor_share'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Debetor',
            new_name='Debtor',
        ),
    ]
