# Generated by Django 4.0.5 on 2022-09-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_debetor_debtor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='unapproved_item',
            field=models.CharField(default='', max_length=30),
        ),
    ]
